In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import math

In [14]:
TransData = pd.read_csv("../data/data_transfer.csv")
TransData.featurevector[5]

'[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1.0, 0.0, 0, 1.1, 0.019529962701121183, 0.19152935673148017, 0.004590572551786353, 1, 0, 0, 0, 0]'

In [19]:
'no' == 'no'

True

In [2]:
InputFile = pd.read_csv("../data/bank-additional-full.csv",sep=';')
DataTranse = DataFrame(index=InputFile.index,columns=['featurevector','y'])
DataTranse.iloc[3].featurevector = [5]
DataTranse.to_csv("./sada.csv")

In [12]:
a = [3,4,5]
b = [1,2,3]
c = np.array(a) - np.array(b)
c

numpy.int64

In [161]:
c ** 2

array([4, 4, 4])

In [40]:
d = [
    [1,2,3],
    [1,2,3],
    [1,2,3]
]
e = np.array(d)
f = 1.0 / ( 1.0 + np.exp( - np.dot( e, np.array([0.1,0.2,0.3]) ) ) )
np.dot(e.T,f)

array([2.40655167, 4.81310333, 7.219655  ])

In [165]:
d.sum(axis=1).argsort()

array([1, 0, 2])

In [134]:
InputFile.shape[0]

41188

In [136]:
math.log2(1 + InputFile.iloc[6].campaign)

1.0

In [3]:
InputFile.std()

age                10.421250
duration          259.279249
campaign            2.770014
pdays             186.910907
previous            0.494901
emp.var.rate        1.570960
cons.price.idx      0.578840
cons.conf.idx       4.628198
euribor3m           1.734447
nr.employed        72.251528
dtype: float64

In [113]:
InputFile.mean()

age                 40.024060
duration           258.285010
campaign             2.567593
pdays              962.475454
previous             0.172963
emp.var.rate         0.081886
cons.price.idx      93.575664
cons.conf.idx      -40.502600
euribor3m            3.621291
nr.employed       5167.035911
dtype: float64

In [117]:
InputFile.iloc[5].marital

'married'

In [138]:
a = [9]
a.extend([5,6,5])
a.append(5.66)
a

[9, 5, 6, 5, 5.66]

In [22]:
Col = InputFile['y']
#Col

In [23]:
Count = Col.value_counts()
#Count.sort_values()
Count.sort_index()

no     36548
yes     4640
Name: y, dtype: int64

In [25]:
for i in range(1,5):
    print(i)

1
2
3
4


In [5]:
"\n" == "\n"

True