In [63]:
import networkx as nx
from pandas import DataFrame
import numpy as np
CoAuthGraph = nx.read_gexf("./B2SimpleCoAuthGraph.gexf")
f = open("./lll",'w')
c = (dict)(nx.degree(CoAuthGraph))
#type(nx.degree(CoAuthGraph))
#for node in CoAuthGraph.nodes:
#d = nx.convert.to_dict_of_lists(CoAuthGraph)
#len(d['Rhodes,JohnL.'])
#len((list)(CoAuthGraph.nodes))
#nx.shortest_path_length(CoAuthGraph,'COLBOURN,CHARLESJOSEPH','COLBOURN,CHARLESJOSEPH')

In [68]:
a = {4,5,6}
a.add(7)
for i in a:
    print(i)

4
5
6
7


In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
CG = nx.read_gexf("./GNCut_CoAuthGraph.gexf")
# nx.number_connected_components(CG)
#float("inf") > 0.5
y = np.array([2,0,1])
z = np.array([4,0,1])
(y ** 2) == z
list(y**2) == list(z)

True

In [49]:
# d = list( CoAuthGraph.nodes() )
# for node in d:
#     if c[node] <= 2:
#         CoAuthGraph.remove_node(node)
# print(CoAuthGraph.number_of_nodes())
# list(dict(CoAuthGraph.degree))
D = np.diag(list(c.values())).astype(float)
D_05 = np.diag(list(c.values())).astype(float)

for i in range(D_05.shape[0]):
    if D_05[i][i] != 0:
        D_05[i][i] = D_05[i][i] ** (-0.5)
# a = nx.adjacency_matrix(CoAuthGraph)
# a.todense()[1].sum()
# np.dot(D_05,np.dot( D_05, D))
np.random.choice(D.shape[0],6)

array([728,  57, 928, 411, 599, 683])

In [5]:
m = nx.modularity_matrix(CoAuthGraph)
m

matrix([[-1.47001612e-02,  9.99360863e-01,  9.99360863e-01, ...,
         -6.39137442e-04, -6.39137442e-04, -6.39137442e-04],
        [ 9.99360863e-01, -2.77885844e-05, -2.77885844e-05, ...,
         -2.77885844e-05, -2.77885844e-05, -2.77885844e-05],
        [ 9.99360863e-01, -2.77885844e-05, -2.77885844e-05, ...,
         -2.77885844e-05, -2.77885844e-05, -2.77885844e-05],
        ...,
        [-6.39137442e-04, -2.77885844e-05, -2.77885844e-05, ...,
         -2.77885844e-05, -2.77885844e-05, -2.77885844e-05],
        [-6.39137442e-04, -2.77885844e-05, -2.77885844e-05, ...,
         -2.77885844e-05, -2.77885844e-05, -2.77885844e-05],
        [-6.39137442e-04, -2.77885844e-05, -2.77885844e-05, ...,
         -2.77885844e-05, -2.77885844e-05, -2.77885844e-05]])

In [84]:
f.write(str(list(nx.connected_components(CoAuthGraph))[1]))
f.close()
CoAuthGraph.nu

In [27]:
b = nx.edge_betweenness_centrality(CoAuthGraph)

In [75]:
bs = sorted(b.items(),key=lambda x:x[1],reverse=True)
bs[0][0][0]
for k,v in b.items():
    print(k[0])

ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
ABBOTT,HARVEYLESLIE
Dierker,PaulF.
Exoo,Geoffrey
HANSON,DENIS
Hare,DonovanR.
Hare,DonovanR.
Katchalski,Meir
Liu,AndyC.F.
MEIR,AMRAM
MEIR,AMRAM
MOON,JOHNW.
MOON,JOHNW.
Riddell,James
SAUER,NORBERTW.
SAUER,NORBERTW.
SUBBARAO,MATUKUMALLIVENKATA
Wang,EdwardTzuHsia
Zhou,Bing^
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JANOSD.
ACZEL,JAN

CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,PETERJ.
CAMERON,

In [48]:
nx.number_connected_components(CoAuthGraph)

14

In [54]:
False == False

True

In [47]:
(list)(nx.connected_components(CoAuthGraph))[5]

{'Adams,C.Raymond', 'CLARKSON,JAMESANDREW', 'Randels,WilliamConrad'}

In [40]:
for c in nx.connected_components(CoAuthGraph):
    print(c)
    input()

{'Hitczenko,Pawel', 'Gooch,AmyAshurst', 'MILLS,GEORGEHARLOW', 'Randall,DanaJ.', 'Kuperberg,Greg', 'Cohen,Shem-Tov', 'Brace,Alan', 'Cowen,RobertH.', 'Perez-Gimenez,Xavier', 'Rami,Yosef', 'PURDY,GEORGEBARRY', 'Hijazi,RolaA.', 'Wang,Renshen', 'Evans,TylerJ.', "MOLLOY,MICHAELSEANO'BRIEN", 'Leech,JohnWatson', 'DiNasso,Mauro', 'Bloom,GaryStuart', 'Sun,Qi^', 'Sharan,Roded', 'Lee,Sin-Min', 'Indyk,Piotr', 'INDLEKOFER,KARL-HEINZ', 'Brandstadt,Andreas', 'Szaniszlo,Zsuzsanna', 'Fay,TempleH.', 'Yan,Xiao-Dan', 'Al-Wahabi,Kais', 'Woodin,W.Hugh', 'OELLERMANN,ORTRUDR.', 'Maass,Wolfgang', 'Louboutin,StephaneR.', 'Imai,Keiko', 'Loeb,Sarah', 'Dudek,Andrzej', 'Wang,Chengu', 'Thomas,Bronwen', 'Sorenson,JonathanPaul', 'Mohamed,ZahraaE.', 'Schonert,Martin', 'Brandt,Stephan', 'Yucas,JosephL.', 'Kannan,Lavanya', 'Mavron,VassiliC.', 'Casanova,Henri', 'Reichardt,BenW.', 'Lempel,Abraham', 'Laishram,Shanta', 'Savicky,Petr', 'Wiener,Janet', 'Owens,MargaretAnn', 'Wilson,DavidA.^', 'Crowe,JohnA.', 'Mahabal,Ashish', 'D


{'Giese,JohnH.', 'Birkhoff,Garrett', 'ALAOGLU,LEONIDAS'}

{'ANNING,NORMANH.'}

{'Straw,Mark', 'Harmon,Gregory', 'Neirynck,Lori', 'ASHBACHER,CHARLESD.', 'Nolte,WilliamD.,Jr.', 'Wilson,Lewis', 'Murthy,Amarnath', 'Le,MaoHua'}


{'BUSOLINI,DONALDTERENCE'}
{'Randels,WilliamConrad', 'CLARKSON,JAMESANDREW', 'Adams,C.Raymond'}


{'Lederer,George', 'Friedlander,FriedrichGerard', 'Auslander,Joseph', 'DOWKER,YAELNAIM'}
{'Pankratz,Alan', 'DUDLEY,UNDERWOOD', 'Tucker,Bessie'}


{'FELDHEIM,ERVIN'}
{'FRIED,HANS'}


{'Rubinstein,ReuvenY.', 'Amdursky,Vardy', 'Tamari,Dov', 'Asaf,Sigal', 'Gal,Shmuel', 'Nikulshin,Ilya', 'Yoeli,Michael', 'ZIV,ABRAHAM', 'Aharoni,Merav', 'Maharik,Ron', 'Nehama,Ilan', 'Fournier,Laurent', 'GINZBURG,ABRAHAM'}
{'Deinert,Erhard', 'Stohr,Alfred', 'Zollner,Joachim', 'HARTTER,ERICH', 'Hofmeister,GerdRolf'}

{'OBLATH,RICHARD'}


{'RIEGER,GEORGJOHANN'}


In [29]:
d = DataFrame(index=(list)(CoAuthGraph.nodes),columns=(list)(CoAuthGraph.nodes))

In [32]:
d['Rhodes,JohnL.']['COLBOURN,CHARLESJOSEPH']

nan